### ISSUE TITLE
Git Large File Storage (LFS) Extension Support

### ISSUE THREAD

**Issue by markusstephanides** [it3xl/git-repo-sync#11]
Hello!

Thanks for that repo, it's almost exactly what we are looking for.

Only thing missing for us would be LFS support. Currently LFS files are not synced which means that the raw pointer files are uploaded without any related LFS files. 

Would it be possible to add this / how much work would it be?

Thanks!

**Comment by it3xl** [comment]
Hello @markusstephanides,

Git Large File Storage (LFS) is an external extension.

Could you advise me on a good documentation about this?

What do you expect from git-repo-sync? What it should to do?
Right now I have no idea what LFS-extension is.
Should git-repo-sync configure remote Git-repositories or do something else?

**Comment by it3xl** [comment]
It's been a long time. I believe it was related to correct configuration of both Git-servers. Good luck in that.
Thank you for using my project.
