### ISSUE TITLE
Bash Credential Helper not working

### ISSUE THREAD

**Issue by ranjan0620** [it3xl/git-repo-sync#13]
I have set use_bash_git_credential_helper value to 1. However it still requires me to input the username and password. I have exported the credentials to env variables as suggested in documentation. As far as I understand setting the "use_bash_git_credential_helper=1" should not require to manually input credentials

**Comment by it3xl** [comment]
I'll answer during the day.

**Comment by ranjan0620** [comment]
ok no problem

**Comment by it3xl** [comment]
@ranjan0620, let me recheck

if you defined something like the following

    #   For the repo in $url_a
    git_cred_username_repo_a=some-login
    git_cred_password_repo_a=some-password
    #   For the repo in $url_b
    git_cred_username_repo_b=another-login
    git_cred_password_repo_b=another-password

please try to add the export expression like this

    #   For the repo in $url_a
    export git_cred_username_repo_a=some-login
    export git_cred_password_repo_a=some-password
    #   For the repo in $url_b
    export git_cred_username_repo_b=another-login
    export git_cred_password_repo_b=another-password

**Comment by ranjan0620** [comment]
@it3xl, did as you suggested. But the issue remains same. Below is the logs after i issue `bash git-sync.sh` command
![error](https://user-images.githubusercontent.com/71761499/219080742-f9cc29ec-0e2c-484f-9a4a-08749dd663b2.jpg)

If you see logs closely, it not only asks for credentials, but the placeholder for credentials are messed up too. I am not sure what I am doing wrong

**Comment by it3xl** [comment]
Ah, this is GitHub, right.
They blocked password authentication some time ago.
You have to use another Git-hosting or accomadeit somehow one of their approaches for authentication.

My [bash-git-credential-helper](https://github.com/it3xl/bash-git-credential-helper) will not help you here, sorry.

**Comment by it3xl** [comment]
I mean that probably you configured everything right but GitHub just blocks authentication by login/password.

**Comment by ranjan0620** [comment]
That's unfortunate But yah I have used git credential helper to store the credentials in my local machine and take it from there and its working fine right now. Thank you for your time and suggestions though. It was helpful. And the script is also great. I think you should work on making the bash credential helper compatible with github too. Just a suggestion :)

**Comment by it3xl** [comment]
You are welcome and thank you, too.

Yeah, great idea, actually. Maybe someday. :) The problem is I'm kind of in another universe right now.

**Comment by ranjan0620** [comment]
hello @it3xl. I came across another issue. I am trying to run the script inside a ubuntu:22.04 container. For some reason its not working. Do I have to do any additional steps like adding additional packages? It does not give any error also. But the same script works fine in my local machine. Please refer to the ss attached below
![image](https://user-images.githubusercontent.com/71761499/220066145-a8d00854-134d-41d6-b28c-40a3c879751a.png)

**Comment by it3xl** [comment]
Hello. Try to check if this file has bash syntax errors.

**Comment by it3xl** [comment]
With GitHub we must use personal access tokens instead of passwords.
So, we create a personal token on GitHub and use it in place of a password.
(Just to mention.)
