### ISSUE TITLE
Tags are not sync.

### ISSUE THREAD

**Issue by Catty82** [it3xl/git-repo-sync#17]
In repo A we have added new tag.
But it is not appear in repo B.

**Comment by it3xl** [comment]
This was intentional.
Sorry for putting it in a depth of README.md during the time.
I've added it to the first lines.

<img width="256" alt="image" src="https://github.com/it3xl/git-repo-sync/assets/919928/ecd727c7-f31d-4e3d-bfe7-b5a3bbca4e64">

**Comment by Catty82** [comment]
Can I use this idea to sync tags?
https://bastide.org/2021/07/13/syncing-git-tags-across-repositories/
Or you have some usefull advice.

**Comment by it3xl** [comment]
looks like. Not sure 100%
Those ideas of adding of two remotes to a local repo always works.
Take any decent Git-UI tool and do it by your hands if you are in doubts.

**Comment by Catty82** [comment]
It works, tags have been synced. Thanks for your cooperation.
