### ISSUE TITLE
One way sync feature

### ISSUE THREAD

**Issue by abratchenko** [it3xl/git-repo-sync#9]
Hey! 
Checked out your project and I can definitely say that it is amazing. Thanks for your work!
Also wanted to propose a feature, to enable "one way sync", in other words a mirror feature that will pull and push changes form Repo A to Repo B.
Thanks in advance for reply!

**Comment by it3xl** [comment]
Hey Artem! @abratchenko

You could already do it on Git and Git-server levels.

- Configure an account with read-only access
- Add a second Git-remote to a repository.
- Do `git fetch` regularly in this repo.

Could you show me some scenarios how you or your team are going to use this feature?
This is important as it affects the implementation.

How would you suggest to configure/enable this feature? (https://github.com/it3xl/git-repo-sync/blob/master/repo_settings/default_sync_project.sh)
Something like this?

    a_to_b_one_way=1

What to do with branches that have conflicting Git-commits in a slave Git-repo?

- Overwrite
- Stop syncing conflicting branches
